a = input("dê o valor lógico A, ou seja, 0 para falso e 1 para verdadeiro ")
b = input("dê o valor lógico B, ou seja, 0 para falso e 1 para verdadeiro ")
c = input("dê o valor lógico C, ou seja, 0 para falso e 1 para verdadeiro ")
print(not not (a and b))
print(not not (a and c))
print(not not (b or c))
print(not not (a and b and c))
print(not (a or b))
print((not a) or (not b))
print(((not a) or (b)) and c)
print((not a) and (not b) and (not c))
print(not(a or b or c))
print(a and False)
print(a and (not a))
print(a or not a)